create database if not exists `unlaGAulas_database`;

use `unlaGAulas_database`;

insert into unlagaulas_database.user values (1,"Perez","Admin@gmail.com","2022-06-07",1,"Jose","12345678","$2a$10$ujL2Bx27KF5IpH/GEqOIMujLhNadkhMEXc8aAPChaW.Ve2ogt5ji6","DNI","2022-06-07","UsuarioAdmin");
insert into unlagaulas_database.user values (2,"Lopez","Usuario1@gmail.com","2022-06-07",1,"Natalia","23456789","$2a$10$ujL2Bx27KF5IpH/GEqOIMujLhNadkhMEXc8aAPChaW.Ve2ogt5ji6","DNI","2022-06-07","UsuarioAuditoria1");
insert into unlagaulas_database.user values (3,"Sanchez","Usuario2@gmail.com","2022-06-07",1,"Juan","12345678","$2a$10$ujL2Bx27KF5IpH/GEqOIMujLhNadkhMEXc8aAPChaW.Ve2ogt5ji6","DNI","2022-06-07","UsuarioAuditoria2");

insert into unlagaulas_database.user_role values (1,"2022-06-07","ROLE_ADMIN","2022-06-07",1);
insert into unlagaulas_database.user_role values (2,"2022-06-07","ROLE_USER","2022-06-07",2);

insert into unlagaulas_database.user_role values (3,"2022-06-07","ROLE_USER","2022-06-07",3);
insert into unlagaulas_database.edificio values (1,"Jose Hernandez");
insert into unlagaulas_database.edificio values (2,"Juana Manso");
insert into unlagaulas_database.edificio values (3,"Leopoldo Marechal");
insert into unlagaulas_database.edificio values (4,"Homero Manzi");
insert into unlagaulas_database.edificio values (5,"Manuel Ugarte");
insert into unlagaulas_database.edificio values (6,"Arturo Jauretche");
insert into unlagaulas_database.edificio values (7,"Raul Scalabrini Ortiz");
insert into unlagaulas_database.aula values (1,1,1);
insert into unlagaulas_database.aula values (2,2,1);
insert into unlagaulas_database.aula values (3,3,1);
insert into unlagaulas_database.aula values (4,4,1);
insert into unlagaulas_database.aula values (5,5,1);
insert into unlagaulas_database.aula values (6,6,1);
insert into unlagaulas_database.aula values (7,7,1);
insert into unlagaulas_database.aula values (8,8,1);
insert into unlagaulas_database.aula values (9,9,1);
insert into unlagaulas_database.aula values (10,10,1);
insert into unlagaulas_database.aula values (11,11,1);
insert into unlagaulas_database.aula values (12,12,1);
insert into unlagaulas_database.aula values (13,13,1);
insert into unlagaulas_database.aula values (14,14,1);
insert into unlagaulas_database.aula values (15,15,1);
insert into unlagaulas_database.aula values (16,1,2);
insert into unlagaulas_database.aula values (17,2,2);
insert into unlagaulas_database.aula values (18,3,2);
insert into unlagaulas_database.aula values (19,4,2);
insert into unlagaulas_database.aula values (20,5,2);
insert into unlagaulas_database.aula values (21,6,2);
insert into unlagaulas_database.aula values (22,7,2);
insert into unlagaulas_database.aula values (23,8,2);
insert into unlagaulas_database.aula values (24,1,3);
insert into unlagaulas_database.aula values (25,2,3);
insert into unlagaulas_database.aula values (26,3,3);
insert into unlagaulas_database.aula values (27,4,3);
insert into unlagaulas_database.aula values (28,5,3);
insert into unlagaulas_database.aula values (29,6,3);
insert into unlagaulas_database.aula values (30,7,3);
insert into unlagaulas_database.aula values (31,8,3);
insert into unlagaulas_database.aula values (32,1,4);
insert into unlagaulas_database.aula values (33,1,5);
insert into unlagaulas_database.aula values (34,1,6);
insert into unlagaulas_database.aula values (35,1,7);
insert into unlagaulas_database.departamento values (1,"Departamento de desarrollo productivo y tecnologico");
insert into unlagaulas_database.carrera values (1,"Licenciatura en sistemas",1);
insert into unlagaulas_database.materia values (1,"8616","Orientacion a objetos 2",1);
insert into unlagaulas_database.materia values (2,"8610","Orientacion a objetos 1",1);
insert into unlagaulas_database.materia values (3,"8603","Matematica 1",1);
insert into unlagaulas_database.materia values (4,"8604","Matematica 2",1);
insert into unlagaulas_database.materia values (5,"8613","Matematica 3",1);
insert into unlagaulas_database.materia values (6,"8618","Base de datos 1",1);
insert into unlagaulas_database.materia values (7,"8609","Algoritmos y estructura de datos",1);
insert into unlagaulas_database.materia values (8,"8619","Proyecto de software",1);

select * from user;
select * from user_role;
select * from nota_pedido_final;
select * from nota_pedido_curso;